week_days:
    days: [1, 2, 3, 4, 5]
    hours: [19, 20, 21]
    courts: [66, 139]
weekends:
    days: [6, 0]  # 0 is Saturday
    hours: [9, 10, 11, 18, 19, 20, 21]
    courts: [66, 139]
# Nvidia:
#     days: [2]
#     hours: [19, 20]
#     courts: [125, 123, 177]
